<?php
$itemOption = $this->getData('item');
$buyRequest = $itemOption->getBuyRequest()->getData();
$pdpdesign = $buyRequest['extra_options'];
$jsonObj = $this->helper('pdp')->decodePdpString($pdpdesign);
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "pdp/images/";
$displayType = "";
$type = Mage::getStoreConfig('pdp/setting/display');
if ($type == "full") {
    $displayType = "display: block;";
} else {
    $displayType = "display: none;";
}
?>
<input type="hidden" value="<?php echo $type ?>" id="display_type" />
<?php if ($type == "full") : ?>
<dt><span style="font-weight: bold"><?php echo $this->__('Customize Design') ?></span></dt>
<?php endif; ?>
<dd>
    <div class="pdp_cart_final_item" alt="<?php echo $itemOption->getId(); ?>">
    <?php
    if (count($jsonObj)){
        for($i=0;$i<count($jsonObj);$i++){
            $pdp_side = $jsonObj[$i];
            $info = $this->helper('pdp')->decodePdpString($pdp_side->json);
            $inlay = explode(',',$info->inlay);
            ?>
            <div class="pdp_side" alt="<?php echo $pdp_side->name; ?>" style="<?php echo $displayType ?>">
                <div id="pdp_cart_view_<?php echo $pdp_side->name.'_' . $itemOption->getId(); ?>" class="img_result" style="position: relative;">
                    <img src="<?php echo $mediaUrl . $pdp_side->img ?>" alt="Image"/>
                    <?php $frontInlayStyle = "position: absolute; width: $inlay[0]px; height: $inlay[1]px; top: $inlay[2]px; left: $inlay[3]px;" ?>
                    <div class="wrap_inlay" style="<?php echo $frontInlayStyle ?> <?php echo ($type == "full") ? "display: block;" : ""; ?>">
                        <?php
                        $items = $info->items;
                        foreach($items as $item){
                            ?>
                            <div scx="<?php echo $item->scx ?>" scy="<?php echo $item->scy ?>" angle="<?php echo $item->angle ?>" class="pdp_item" style="<?php echo $item->css ?>">
                                <?php if($item->type == 'text'){ ?>
                                    <p style="<?php echo $item->itemcss ?>"><?php echo $item->text ?></p>
                                <?php } ?>
                                <?php if($item->type == 'image'){ ?>
                                    <img src="<?php echo $item->path ?>" style="<?php echo $item->itemcss ?>" />
                                <?php } ?>
                            </div>
                        <?php }
                        ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
    </div>
</dd>


