<?php
$_item = $this->getData('item');
$productId = $_item->getProductId();
$orderId = $_item->getOrderId();
$itemId = $_item->getId();
$baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK);
$jsonString = Mage::helper('pdp')->getOrderItemString($orderId, $itemId);
?>
<?php if ($jsonString != NULL) : ?>
<dt><span style="font-weight: bold; font-style: italic;"><?php echo $this->__('Customize Design') ?></span></dt>
<dd style="margin: 0px; padding: 0px;">
   <?php
		echo "<a style='margin:0;padding:0 0 0 9px' target='_blank' href='". $baseUrl . "pdp/view/finalDesign/product-id/$productId/order-id/$orderId/item-id/$itemId" . "'>Click here to review your design!</a>"; 
	?>
</dd>
<?php endif; ?>